# Generated by Django 6.0 on 2025-12-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(help_text='HEX color code or gradient, e.g., #FFFFFF or #FFB6C1,#000000', max_length=50),
        ),
    ]
