# Generated by Django 6.0 on 2026-01-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount_amount_order_shipping_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='iphone_number',
            new_name='phone_number',
        ),
    ]
